<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Country;
use Illuminate\Database\Seeder;

class MinyaCitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // إنشاء دولة ألمانيا (Germany) إذا لم تكن موجودة
        $germany = Country::firstOrCreate(
            [],
            [
                'name' => [
                    'en' => 'Germany',
                    'ar' => 'ألمانيا',
                    'de' => 'Deutschland',
                    'fr' => 'Allemagne',
                    'it' => 'Germania',
                ]
            ]
        );

        // قائمة كاملة بمدن ألمانيا
        $cities = [
            [
                'en' => 'Berlin',
                'ar' => 'برلين',
                'de' => 'Berlin',
                'fr' => 'Berlin',
                'it' => 'Berlino',
            ],
            [
                'en' => 'Hamburg',
                'ar' => 'هامبورغ',
                'de' => 'Hamburg',
                'fr' => 'Hambourg',
                'it' => 'Amburgo',
            ],
            [
                'en' => 'Munich',
                'ar' => 'ميونيخ',
                'de' => 'München',
                'fr' => 'Munich',
                'it' => 'Monaco di Baviera',
            ],
            [
                'en' => 'Cologne',
                'ar' => 'كولونيا',
                'de' => 'Köln',
                'fr' => 'Cologne',
                'it' => 'Colonia',
            ],
            [
                'en' => 'Frankfurt am Main',
                'ar' => 'فرانكفورت أم ماين',
                'de' => 'Frankfurt am Main',
                'fr' => 'Francfort-sur-le-Main',
                'it' => 'Francoforte sul Meno',
            ],
            [
                'en' => 'Düsseldorf',
                'ar' => 'دوسلدورف',
                'de' => 'Düsseldorf',
                'fr' => 'Düsseldorf',
                'it' => 'Düsseldorf',
            ],
            [
                'en' => 'Stuttgart',
                'ar' => 'شتوتغارت',
                'de' => 'Stuttgart',
                'fr' => 'Stuttgart',
                'it' => 'Stoccarda',
            ],
            [
                'en' => 'Leipzig',
                'ar' => 'لايبزِج',
                'de' => 'Leipzig',
                'fr' => 'Leipzig',
                'it' => 'Lipsia',
            ],
            [
                'en' => 'Dresden',
                'ar' => 'دريسدن',
                'de' => 'Dresden',
                'fr' => 'Dresde',
                'it' => 'Dresda',
            ],
            [
                'en' => 'Dortmund',
                'ar' => 'دورتموند',
                'de' => 'Dortmund',
                'fr' => 'Dortmund',
                'it' => 'Dortmund',
            ],
            [
                'en' => 'Essen',
                'ar' => 'إسن',
                'de' => 'Essen',
                'fr' => 'Essen',
                'it' => 'Essen',
            ],
            [
                'en' => 'Bremen',
                'ar' => 'بريمن',
                'de' => 'Bremen',
                'fr' => 'Brême',
                'it' => 'Brema',
            ],
            [
                'en' => 'Hanover',
                'ar' => 'هانوفر',
                'de' => 'Hannover',
                'fr' => 'Hanovre',
                'it' => 'Hannover',
            ],
            [
                'en' => 'Duisburg',
                'ar' => 'دويسبورغ',
                'de' => 'Duisburg',
                'fr' => 'Duisburg',
                'it' => 'Duisburg',
            ],
            [
                'en' => 'Nuremberg',
                'ar' => 'نورنبرغ',
                'de' => 'Nürnberg',
                'fr' => 'Nuremberg',
                'it' => 'Norimberga',
            ],
            [
                'en' => 'Bochum',
                'ar' => 'بوخوم',
                'de' => 'Bochum',
                'fr' => 'Bochum',
                'it' => 'Bochum',
            ],
            [
                'en' => 'Wuppertal',
                'ar' => 'فوبرتال',
                'de' => 'Wuppertal',
                'fr' => 'Wuppertal',
                'it' => 'Wuppertal',
            ],
            [
                'en' => 'Bielefeld',
                'ar' => 'بيليفيلد',
                'de' => 'Bielefeld',
                'fr' => 'Bielefeld',
                'it' => 'Bielefeld',
            ],
            [
                'en' => 'Bonn',
                'ar' => 'بون',
                'de' => 'Bonn',
                'fr' => 'Bonn',
                'it' => 'Bonn',
            ],
            [
                'en' => 'Münster',
                'ar' => 'مونستر',
                'de' => 'Münster',
                'fr' => 'Münster',
                'it' => 'Münster',
            ],
            [
                'en' => 'Karlsruhe',
                'ar' => 'كارلسروه',
                'de' => 'Karlsruhe',
                'fr' => 'Karlsruhe',
                'it' => 'Karlsruhe',
            ],
            [
                'en' => 'Mannheim',
                'ar' => 'مانهايم',
                'de' => 'Mannheim',
                'fr' => 'Mannheim',
                'it' => 'Mannheim',
            ],
            [
                'en' => 'Augsburg',
                'ar' => 'آوغسبورغ',
                'de' => 'Augsburg',
                'fr' => 'Augsbourg',
                'it' => 'Augusta',
            ],
            [
                'en' => 'Wiesbaden',
                'ar' => 'فيسبادن',
                'de' => 'Wiesbaden',
                'fr' => 'Wiesbaden',
                'it' => 'Wiesbaden',
            ],
            [
                'en' => 'Gelsenkirchen',
                'ar' => 'جيلسنكيرشن',
                'de' => 'Gelsenkirchen',
                'fr' => 'Gelsenkirchen',
                'it' => 'Gelsenkirchen',
            ],
            [
                'en' => 'Mönchengladbach',
                'ar' => 'مونشنغلادباخ',
                'de' => 'Mönchengladbach',
                'fr' => 'Mönchengladbach',
                'it' => 'Mönchengladbach',
            ],
            [
                'en' => 'Braunschweig',
                'ar' => 'براونشفايغ',
                'de' => 'Braunschweig',
                'fr' => 'Brunswick',
                'it' => 'Brunswick',
            ],
            [
                'en' => 'Chemnitz',
                'ar' => 'كيمنتس',
                'de' => 'Chemnitz',
                'fr' => 'Chemnitz',
                'it' => 'Chemnitz',
            ],
            [
                'en' => 'Kiel',
                'ar' => 'كيل',
                'de' => 'Kiel',
                'fr' => 'Kiel',
                'it' => 'Kiel',
            ],
            [
                'en' => 'Aachen',
                'ar' => 'آخن',
                'de' => 'Aachen',
                'fr' => 'Aix-la-Chapelle',
                'it' => 'Aquisgrana',
            ],
            // المدن الفرعية
            [
                'en' => 'Halle',
                'ar' => 'هاله',
                'de' => 'Halle',
                'fr' => 'Halle',
                'it' => 'Halle',
            ],
            [
                'en' => 'Magdeburg',
                'ar' => 'ماغدبورغ',
                'de' => 'Magdeburg',
                'fr' => 'Magdebourg',
                'it' => 'Magdeburgo',
            ],
            [
                'en' => 'Freiburg',
                'ar' => 'فرايبورغ',
                'de' => 'Freiburg',
                'fr' => 'Fribourg-en-Brisgau',
                'it' => 'Friburgo in Brisgovia',
            ],
            [
                'en' => 'Krefeld',
                'ar' => 'كريفلد',
                'de' => 'Krefeld',
                'fr' => 'Krefeld',
                'it' => 'Krefeld',
            ],
            [
                'en' => 'Lübeck',
                'ar' => 'لوبيك',
                'de' => 'Lübeck',
                'fr' => 'Lübeck',
                'it' => 'Lubecca',
            ],
            [
                'en' => 'Oberhausen',
                'ar' => 'أوبرهاوزن',
                'de' => 'Oberhausen',
                'fr' => 'Oberhausen',
                'it' => 'Oberhausen',
            ],
            [
                'en' => 'Erfurt',
                'ar' => 'إرفورت',
                'de' => 'Erfurt',
                'fr' => 'Erfurt',
                'it' => 'Erfurt',
            ],
            [
                'en' => 'Mainz',
                'ar' => 'ماينتس',
                'de' => 'Mainz',
                'fr' => 'Mayence',
                'it' => 'Magonza',
            ],
            [
                'en' => 'Rostock',
                'ar' => 'روستوك',
                'de' => 'Rostock',
                'fr' => 'Rostock',
                'it' => 'Rostock',
            ],
            [
                'en' => 'Kassel',
                'ar' => 'كاسل',
                'de' => 'Kassel',
                'fr' => 'Cassel',
                'it' => 'Kassel',
            ],
            [
                'en' => 'Hagen',
                'ar' => 'هاغن',
                'de' => 'Hagen',
                'fr' => 'Hagen',
                'it' => 'Hagen',
            ],
            [
                'en' => 'Hamm',
                'ar' => 'هام',
                'de' => 'Hamm',
                'fr' => 'Hamm',
                'it' => 'Hamm',
            ],
            [
                'en' => 'Saarbrücken',
                'ar' => 'زاربروكن',
                'de' => 'Saarbrücken',
                'fr' => 'Sarrebruck',
                'it' => 'Saarbrücken',
            ],
            [
                'en' => 'Mülheim',
                'ar' => 'مولهايم',
                'de' => 'Mülheim',
                'fr' => 'Mülheim',
                'it' => 'Mülheim',
            ],
            [
                'en' => 'Potsdam',
                'ar' => 'بوتسدام',
                'de' => 'Potsdam',
                'fr' => 'Potsdam',
                'it' => 'Potsdam',
            ],
            [
                'en' => 'Ludwigshafen',
                'ar' => 'لودفيغسهافن',
                'de' => 'Ludwigshafen',
                'fr' => 'Ludwigshafen',
                'it' => 'Ludwigshafen',
            ],
            [
                'en' => 'Oldenburg',
                'ar' => 'أولدنبورغ',
                'de' => 'Oldenburg',
                'fr' => 'Oldenbourg',
                'it' => 'Oldenburg',
            ],
            [
                'en' => 'Leverkusen',
                'ar' => 'ليفركوزن',
                'de' => 'Leverkusen',
                'fr' => 'Leverkusen',
                'it' => 'Leverkusen',
            ],
            [
                'en' => 'Osnabrück',
                'ar' => 'أوسنابروك',
                'de' => 'Osnabrück',
                'fr' => 'Osnabrück',
                'it' => 'Osnabrück',
            ],
            [
                'en' => 'Solingen',
                'ar' => 'زولينغن',
                'de' => 'Solingen',
                'fr' => 'Solingen',
                'it' => 'Solingen',
            ],
            [
                'en' => 'Heidelberg',
                'ar' => 'هايدلبرغ',
                'de' => 'Heidelberg',
                'fr' => 'Heidelberg',
                'it' => 'Heidelberg',
            ],
            [
                'en' => 'Herne',
                'ar' => 'هيرنه',
                'de' => 'Herne',
                'fr' => 'Herne',
                'it' => 'Herne',
            ],
            [
                'en' => 'Neuss',
                'ar' => 'نويس',
                'de' => 'Neuss',
                'fr' => 'Neuss',
                'it' => 'Neuss',
            ],
            [
                'en' => 'Darmstadt',
                'ar' => 'دارمشتات',
                'de' => 'Darmstadt',
                'fr' => 'Darmstadt',
                'it' => 'Darmstadt',
            ],
            [
                'en' => 'Paderborn',
                'ar' => 'بادربورن',
                'de' => 'Paderborn',
                'fr' => 'Paderborn',
                'it' => 'Paderborn',
            ],
            [
                'en' => 'Regensburg',
                'ar' => 'ريغنسبورغ',
                'de' => 'Regensburg',
                'fr' => 'Ratisbonne',
                'it' => 'Ratisbona',
            ],
            [
                'en' => 'Ingolstadt',
                'ar' => 'إنغولشتات',
                'de' => 'Ingolstadt',
                'fr' => 'Ingolstadt',
                'it' => 'Ingolstadt',
            ],
            [
                'en' => 'Würzburg',
                'ar' => 'فورتسبورغ',
                'de' => 'Würzburg',
                'fr' => 'Wurtzbourg',
                'it' => 'Würzburg',
            ],
            [
                'en' => 'Fürth',
                'ar' => 'فورت',
                'de' => 'Fürth',
                'fr' => 'Fürth',
                'it' => 'Fürth',
            ],
            [
                'en' => 'Wolfsburg',
                'ar' => 'فولفسبورغ',
                'de' => 'Wolfsburg',
                'fr' => 'Wolfsburg',
                'it' => 'Wolfsburg',
            ],
            [
                'en' => 'Offenbach',
                'ar' => 'أوفنباخ',
                'de' => 'Offenbach',
                'fr' => 'Offenbach',
                'it' => 'Offenbach',
            ],
            [
                'en' => 'Ulm',
                'ar' => 'أولم',
                'de' => 'Ulm',
                'fr' => 'Ulm',
                'it' => 'Ulma',
            ],
            [
                'en' => 'Heilbronn',
                'ar' => 'هايلبرون',
                'de' => 'Heilbronn',
                'fr' => 'Heilbronn',
                'it' => 'Heilbronn',
            ],
            [
                'en' => 'Pforzheim',
                'ar' => 'فورزهايم',
                'de' => 'Pforzheim',
                'fr' => 'Pforzheim',
                'it' => 'Pforzheim',
            ],
            [
                'en' => 'Göttingen',
                'ar' => 'غوتنغن',
                'de' => 'Göttingen',
                'fr' => 'Göttingen',
                'it' => 'Gottinga',
            ],
            [
                'en' => 'Bottrop',
                'ar' => 'بوتروب',
                'de' => 'Bottrop',
                'fr' => 'Bottrop',
                'it' => 'Bottrop',
            ],
            [
                'en' => 'Trier',
                'ar' => 'ترير',
                'de' => 'Trier',
                'fr' => 'Trèves',
                'it' => 'Treviri',
            ],
            [
                'en' => 'Recklinghausen',
                'ar' => 'ريكلينغهاوزن',
                'de' => 'Recklinghausen',
                'fr' => 'Recklinghausen',
                'it' => 'Recklinghausen',
            ],
            [
                'en' => 'Reutlingen',
                'ar' => 'رويتلينغن',
                'de' => 'Reutlingen',
                'fr' => 'Reutlingen',
                'it' => 'Reutlingen',
            ],
            [
                'en' => 'Bremerhaven',
                'ar' => 'بريمرهافن',
                'de' => 'Bremerhaven',
                'fr' => 'Bremerhaven',
                'it' => 'Bremerhaven',
            ],
            [
                'en' => 'Koblenz',
                'ar' => 'كوبلنتس',
                'de' => 'Koblenz',
                'fr' => 'Coblence',
                'it' => 'Coblenza',
            ],
            [
                'en' => 'Bergisch Gladbach',
                'ar' => 'برغيش غلادباخ',
                'de' => 'Bergisch Gladbach',
                'fr' => 'Bergisch Gladbach',
                'it' => 'Bergisch Gladbach',
            ],
            [
                'en' => 'Jena',
                'ar' => 'ينا',
                'de' => 'Jena',
                'fr' => 'Iéna',
                'it' => 'Jena',
            ],
            [
                'en' => 'Remscheid',
                'ar' => 'ريمشايد',
                'de' => 'Remscheid',
                'fr' => 'Remscheid',
                'it' => 'Remscheid',
            ],
            [
                'en' => 'Erlangen',
                'ar' => 'إرلانغن',
                'de' => 'Erlangen',
                'fr' => 'Erlangen',
                'it' => 'Erlangen',
            ],
            [
                'en' => 'Moers',
                'ar' => 'مورس',
                'de' => 'Moers',
                'fr' => 'Moers',
                'it' => 'Moers',
            ],
            [
                'en' => 'Siegen',
                'ar' => 'زيغن',
                'de' => 'Siegen',
                'fr' => 'Siegen',
                'it' => 'Siegen',
            ],
            [
                'en' => 'Hildesheim',
                'ar' => 'هيلدسهايم',
                'de' => 'Hildesheim',
                'fr' => 'Hildesheim',
                'it' => 'Hildesheim',
            ],
            [
                'en' => 'Salzgitter',
                'ar' => 'زالزغيتر',
                'de' => 'Salzgitter',
                'fr' => 'Salzgitter',
                'it' => 'Salzgitter',
            ],
            [
                'en' => 'Cottbus',
                'ar' => 'كوتبوس',
                'de' => 'Cottbus',
                'fr' => 'Cottbus',
                'it' => 'Cottbus',
            ],
            [
                'en' => 'Gera',
                'ar' => 'غيرا',
                'de' => 'Gera',
                'fr' => 'Gera',
                'it' => 'Gera',
            ],
            [
                'en' => 'Kaiserslautern',
                'ar' => 'كايزرسلاوترن',
                'de' => 'Kaiserslautern',
                'fr' => 'Kaiserslautern',
                'it' => 'Kaiserslautern',
            ],
            [
                'en' => 'Schwerin',
                'ar' => 'شفيرين',
                'de' => 'Schwerin',
                'fr' => 'Schwerin',
                'it' => 'Schwerin',
            ],
            [
                'en' => 'Witten',
                'ar' => 'فيتن',
                'de' => 'Witten',
                'fr' => 'Witten',
                'it' => 'Witten',
            ],
            [
                'en' => 'Gütersloh',
                'ar' => 'غوترسلوه',
                'de' => 'Gütersloh',
                'fr' => 'Gütersloh',
                'it' => 'Gütersloh',
            ],
            [
                'en' => 'Iserlohn',
                'ar' => 'إيزرلون',
                'de' => 'Iserlohn',
                'fr' => 'Iserlohn',
                'it' => 'Iserlohn',
            ],
            [
                'en' => 'Zwickau',
                'ar' => 'تسفيكاو',
                'de' => 'Zwickau',
                'fr' => 'Zwickau',
                'it' => 'Zwickau',
            ],
            [
                'en' => 'Düren',
                'ar' => 'دورن',
                'de' => 'Düren',
                'fr' => 'Düren',
                'it' => 'Düren',
            ],
            [
                'en' => 'Tübingen',
                'ar' => 'تيوبنغن',
                'de' => 'Tübingen',
                'fr' => 'Tübingen',
                'it' => 'Tubinga',
            ],
            [
                'en' => 'Flensburg',
                'ar' => 'فلنسبورغ',
                'de' => 'Flensburg',
                'fr' => 'Flensbourg',
                'it' => 'Flensburg',
            ],
            [
                'en' => 'Lüneburg',
                'ar' => 'لونبورغ',
                'de' => 'Lüneburg',
                'fr' => 'Lunebourg',
                'it' => 'Luneburgo',
            ],
            [
                'en' => 'Villingen-Schwenningen',
                'ar' => 'فيلينغن-شفنينغن',
                'de' => 'Villingen-Schwenningen',
                'fr' => 'Villingen-Schwenningen',
                'it' => 'Villingen-Schwenningen',
            ],
            [
                'en' => 'Gießen',
                'ar' => 'غيسن',
                'de' => 'Gießen',
                'fr' => 'Giessen',
                'it' => 'Gießen',
            ],
            [
                'en' => 'Marl',
                'ar' => 'مارل',
                'de' => 'Marl',
                'fr' => 'Marl',
                'it' => 'Marl',
            ],
            [
                'en' => 'Konstanz',
                'ar' => 'كونستانتس',
                'de' => 'Konstanz',
                'fr' => 'Constance',
                'it' => 'Costanza',
            ],
            [
                'en' => 'Minden',
                'ar' => 'ميندن',
                'de' => 'Minden',
                'fr' => 'Minden',
                'it' => 'Minden',
            ],
            [
                'en' => 'Lüdenscheid',
                'ar' => 'لودنشايد',
                'de' => 'Lüdenscheid',
                'fr' => 'Lüdenscheid',
                'it' => 'Lüdenscheid',
            ],
            [
                'en' => 'Velbert',
                'ar' => 'فيلبرت',
                'de' => 'Velbert',
                'fr' => 'Velbert',
                'it' => 'Velbert',
            ],
            [
                'en' => 'Neumünster',
                'ar' => 'نويمونستر',
                'de' => 'Neumünster',
                'fr' => 'Neumünster',
                'it' => 'Neumünster',
            ],
            [
                'en' => 'Unna',
                'ar' => 'أونا',
                'de' => 'Unna',
                'fr' => 'Unna',
                'it' => 'Unna',
            ],
            [
                'en' => 'Delmenhorst',
                'ar' => 'دلمنهورست',
                'de' => 'Delmenhorst',
                'fr' => 'Delmenhorst',
                'it' => 'Delmenhorst',
            ],
            [
                'en' => 'Wilhelmshaven',
                'ar' => 'فيلهلمسهافن',
                'de' => 'Wilhelmshaven',
                'fr' => 'Wilhelmshaven',
                'it' => 'Wilhelmshaven',
            ],
            [
                'en' => 'Viersen',
                'ar' => 'فيرزن',
                'de' => 'Viersen',
                'fr' => 'Viersen',
                'it' => 'Viersen',
            ],
            [
                'en' => 'Gladbeck',
                'ar' => 'غلادبيك',
                'de' => 'Gladbeck',
                'fr' => 'Gladbeck',
                'it' => 'Gladbeck',
            ],
            [
                'en' => 'Dorsten',
                'ar' => 'دورستن',
                'de' => 'Dorsten',
                'fr' => 'Dorsten',
                'it' => 'Dorsten',
            ],
            [
                'en' => 'Rheine',
                'ar' => 'راينه',
                'de' => 'Rheine',
                'fr' => 'Rheine',
                'it' => 'Rheine',
            ],
            [
                'en' => 'Detmold',
                'ar' => 'دتمولد',
                'de' => 'Detmold',
                'fr' => 'Detmold',
                'it' => 'Detmold',
            ],
            [
                'en' => 'Troisdorf',
                'ar' => 'ترويسدورف',
                'de' => 'Troisdorf',
                'fr' => 'Troisdorf',
                'it' => 'Troisdorf',
            ],
            [
                'en' => 'Castrop-Rauxel',
                'ar' => 'كاستروب-راوكسل',
                'de' => 'Castrop-Rauxel',
                'fr' => 'Castrop-Rauxel',
                'it' => 'Castrop-Rauxel',
            ],
            [
                'en' => 'Lüneburg',
                'ar' => 'لونبورغ',
                'de' => 'Lüneburg',
                'fr' => 'Lunebourg',
                'it' => 'Luneburgo',
            ],
            [
                'en' => 'Marburg',
                'ar' => 'ماربورغ',
                'de' => 'Marburg',
                'fr' => 'Marbourg',
                'it' => 'Marburgo',
            ],
            [
                'en' => 'Arnsberg',
                'ar' => 'أرنسبيرغ',
                'de' => 'Arnsberg',
                'fr' => 'Arnsberg',
                'it' => 'Arnsberg',
            ],
            [
                'en' => 'Lüdenscheid',
                'ar' => 'لودنشايد',
                'de' => 'Lüdenscheid',
                'fr' => 'Lüdenscheid',
                'it' => 'Lüdenscheid',
            ],
            [
                'en' => 'Bamberg',
                'ar' => 'بامبرغ',
                'de' => 'Bamberg',
                'fr' => 'Bamberg',
                'it' => 'Bamberga',
            ],
            [
                'en' => 'Bayreuth',
                'ar' => 'بايرويت',
                'de' => 'Bayreuth',
                'fr' => 'Bayreuth',
                'it' => 'Bayreuth',
            ],
            [
                'en' => 'Aschaffenburg',
                'ar' => 'آشافنبورغ',
                'de' => 'Aschaffenburg',
                'fr' => 'Aschaffenbourg',
                'it' => 'Aschaffenburg',
            ],
            [
                'en' => 'Landshut',
                'ar' => 'لاندسهوت',
                'de' => 'Landshut',
                'fr' => 'Landshut',
                'it' => 'Landshut',
            ],
            [
                'en' => 'Kempten',
                'ar' => 'كيمبتن',
                'de' => 'Kempten',
                'fr' => 'Kempten',
                'it' => 'Kempten',
            ],
            [
                'en' => 'Rosenheim',
                'ar' => 'روزنهايم',
                'de' => 'Rosenheim',
                'fr' => 'Rosenheim',
                'it' => 'Rosenheim',
            ],
            [
                'en' => 'Schwäbisch Gmünd',
                'ar' => 'شفابيش غموند',
                'de' => 'Schwäbisch Gmünd',
                'fr' => 'Schwäbisch Gmünd',
                'it' => 'Schwäbisch Gmünd',
            ],
            [
                'en' => 'Fulda',
                'ar' => 'فولدا',
                'de' => 'Fulda',
                'fr' => 'Fulda',
                'it' => 'Fulda',
            ],
            [
                'en' => 'Ravensburg',
                'ar' => 'رافنسبورغ',
                'de' => 'Ravensburg',
                'fr' => 'Ravensburg',
                'it' => 'Ravensburg',
            ],
            [
                'en' => 'Friedrichshafen',
                'ar' => 'فريدريشهافن',
                'de' => 'Friedrichshafen',
                'fr' => 'Friedrichshafen',
                'it' => 'Friedrichshafen',
            ],
            [
                'en' => 'Weimar',
                'ar' => 'فايمار',
                'de' => 'Weimar',
                'fr' => 'Weimar',
                'it' => 'Weimar',
            ],
            [
                'en' => 'Eisenach',
                'ar' => 'آيزناخ',
                'de' => 'Eisenach',
                'fr' => 'Eisenach',
                'it' => 'Eisenach',
            ],
            [
                'en' => 'Gotha',
                'ar' => 'غوتا',
                'de' => 'Gotha',
                'fr' => 'Gotha',
                'it' => 'Gotha',
            ],
            [
                'en' => 'Meiningen',
                'ar' => 'ماينينغن',
                'de' => 'Meiningen',
                'fr' => 'Meiningen',
                'it' => 'Meiningen',
            ],
            [
                'en' => 'Suhl',
                'ar' => 'زول',
                'de' => 'Suhl',
                'fr' => 'Suhl',
                'it' => 'Suhl',
            ],
            [
                'en' => 'Nordhausen',
                'ar' => 'نوردهاوزن',
                'de' => 'Nordhausen',
                'fr' => 'Nordhausen',
                'it' => 'Nordhausen',
            ],
            [
                'en' => 'Altenburg',
                'ar' => 'آلتنبورغ',
                'de' => 'Altenburg',
                'fr' => 'Altenburg',
                'it' => 'Altenburg',
            ],
            [
                'en' => 'Mühlhausen',
                'ar' => 'مولهاوزن',
                'de' => 'Mühlhausen',
                'fr' => 'Mühlhausen',
                'it' => 'Mühlhausen',
            ],
            [
                'en' => 'Sondershausen',
                'ar' => 'زوندرسهاوزن',
                'de' => 'Sondershausen',
                'fr' => 'Sondershausen',
                'it' => 'Sondershausen',
            ],
            [
                'en' => 'Saalfeld',
                'ar' => 'زالفلد',
                'de' => 'Saalfeld',
                'fr' => 'Saalfeld',
                'it' => 'Saalfeld',
            ],
            [
                'en' => 'Ilmenau',
                'ar' => 'إلمناو',
                'de' => 'Ilmenau',
                'fr' => 'Ilmenau',
                'it' => 'Ilmenau',
            ],
            [
                'en' => 'Arnstadt',
                'ar' => 'أرنشتات',
                'de' => 'Arnstadt',
                'fr' => 'Arnstadt',
                'it' => 'Arnstadt',
            ],
            [
                'en' => 'Sonneberg',
                'ar' => 'زونيبرغ',
                'de' => 'Sonneberg',
                'fr' => 'Sonneberg',
                'it' => 'Sonneberg',
            ],
            [
                'en' => 'Sömmerda',
                'ar' => 'زوميردا',
                'de' => 'Sömmerda',
                'fr' => 'Sömmerda',
                'it' => 'Sömmerda',
            ],
            [
                'en' => 'Leinefelde-Worbis',
                'ar' => 'لاينفيلده-فوربيس',
                'de' => 'Leinefelde-Worbis',
                'fr' => 'Leinefelde-Worbis',
                'it' => 'Leinefelde-Worbis',
            ],
            [
                'en' => 'Heilbad Heiligenstadt',
                'ar' => 'هايلباد هايليغنشتات',
                'de' => 'Heilbad Heiligenstadt',
                'fr' => 'Heilbad Heiligenstadt',
                'it' => 'Heilbad Heiligenstadt',
            ],
            [
                'en' => 'Bad Langensalza',
                'ar' => 'باد لانغنزالزا',
                'de' => 'Bad Langensalza',
                'fr' => 'Bad Langensalza',
                'it' => 'Bad Langensalza',
            ],
            [
                'en' => 'Bad Salzungen',
                'ar' => 'باد زالتسونغن',
                'de' => 'Bad Salzungen',
                'fr' => 'Bad Salzungen',
                'it' => 'Bad Salzungen',
            ],
            [
                'en' => 'Greiz',
                'ar' => 'غرايتس',
                'de' => 'Greiz',
                'fr' => 'Greiz',
                'it' => 'Greiz',
            ],
            [
                'en' => 'Zeulenroda-Triebes',
                'ar' => 'تسويلنرودا-تريبيس',
                'de' => 'Zeulenroda-Triebes',
                'fr' => 'Zeulenroda-Triebes',
                'it' => 'Zeulenroda-Triebes',
            ],
            [
                'en' => 'Schmalkalden',
                'ar' => 'شملكالدن',
                'de' => 'Schmalkalden',
                'fr' => 'Schmalkalden',
                'it' => 'Schmalkalden',
            ],
            [
                'en' => 'Waltershausen',
                'ar' => 'فالترسهاوزن',
                'de' => 'Waltershausen',
                'fr' => 'Waltershausen',
                'it' => 'Waltershausen',
            ],
            [
                'en' => 'Bad Frankenhausen',
                'ar' => 'باد فرانكنهاوزن',
                'de' => 'Bad Frankenhausen',
                'fr' => 'Bad Frankenhausen',
                'it' => 'Bad Frankenhausen',
            ],
            [
                'en' => 'Sondershausen',
                'ar' => 'زوندرسهاوزن',
                'de' => 'Sondershausen',
                'fr' => 'Sondershausen',
                'it' => 'Sondershausen',
            ],
            [
                'en' => 'Eisfeld',
                'ar' => 'آيسفيلد',
                'de' => 'Eisfeld',
                'fr' => 'Eisfeld',
                'it' => 'Eisfeld',
            ],
            [
                'en' => 'Hildburghausen',
                'ar' => 'هيلدبورغهاوزن',
                'de' => 'Hildburghausen',
                'fr' => 'Hildburghausen',
                'it' => 'Hildburghausen',
            ],
            [
                'en' => 'Lauterbach',
                'ar' => 'لاوترباخ',
                'de' => 'Lauterbach',
                'fr' => 'Lauterbach',
                'it' => 'Lauterbach',
            ],
            [
                'en' => 'Schleusingen',
                'ar' => 'شلاوزنغن',
                'de' => 'Schleusingen',
                'fr' => 'Schleusingen',
                'it' => 'Schleusingen',
            ],
            [
                'en' => 'Oberhof',
                'ar' => 'أوبرهوف',
                'de' => 'Oberhof',
                'fr' => 'Oberhof',
                'it' => 'Oberhof',
            ],
            [
                'en' => 'Tambach-Dietharz',
                'ar' => 'تامباخ-ديتهارتس',
                'de' => 'Tambach-Dietharz',
                'fr' => 'Tambach-Dietharz',
                'it' => 'Tambach-Dietharz',
            ],
            [
                'en' => 'Steinbach-Hallenberg',
                'ar' => 'شتاينباخ-هالنبرغ',
                'de' => 'Steinbach-Hallenberg',
                'fr' => 'Steinbach-Hallenberg',
                'it' => 'Steinbach-Hallenberg',
            ],
            [
                'en' => 'Brotterode',
                'ar' => 'بروتروده',
                'de' => 'Brotterode',
                'fr' => 'Brotterode',
                'it' => 'Brotterode',
            ],
            [
                'en' => 'Trusetal',
                'ar' => 'تروزيتال',
                'de' => 'Trusetal',
                'fr' => 'Trusetal',
                'it' => 'Trusetal',
            ],
            [
                'en' => 'Zella-Mehlis',
                'ar' => 'تسيلا-ميهليس',
                'de' => 'Zella-Mehlis',
                'fr' => 'Zella-Mehlis',
                'it' => 'Zella-Mehlis',
            ],
            [
                'en' => 'Oberweid',
                'ar' => 'أوبرفايد',
                'de' => 'Oberweid',
                'fr' => 'Oberweid',
                'it' => 'Oberweid',
            ],
            [
                'en' => 'Wasungen',
                'ar' => 'فازونغن',
                'de' => 'Wasungen',
                'fr' => 'Wasungen',
                'it' => 'Wasungen',
            ],
            [
                'en' => 'Kaltennordheim',
                'ar' => 'كالتنوردهايم',
                'de' => 'Kaltennordheim',
                'fr' => 'Kaltennordheim',
                'it' => 'Kaltennordheim',
            ],
            [
                'en' => 'Geisa',
                'ar' => 'غايسا',
                'de' => 'Geisa',
                'fr' => 'Geisa',
                'it' => 'Geisa',
            ],
            [
                'en' => 'Stadtlengsfeld',
                'ar' => 'شتادتلنغسفيلد',
                'de' => 'Stadtlengsfeld',
                'fr' => 'Stadtlengsfeld',
                'it' => 'Stadtlengsfeld',
            ],
            [
                'en' => 'Vacha',
                'ar' => 'فاخا',
                'de' => 'Vacha',
                'fr' => 'Vacha',
                'it' => 'Vacha',
            ],
            [
                'en' => 'Dermbach',
                'ar' => 'ديرمباخ',
                'de' => 'Dermbach',
                'fr' => 'Dermbach',
                'it' => 'Dermbach',
            ],
            [
                'en' => 'Tann',
                'ar' => 'تان',
                'de' => 'Tann',
                'fr' => 'Tann',
                'it' => 'Tann',
            ],
            [
                'en' => 'Hünfeld',
                'ar' => 'هونفيلد',
                'de' => 'Hünfeld',
                'fr' => 'Hünfeld',
                'it' => 'Hünfeld',
            ],
            [
                'en' => 'Bad Hersfeld',
                'ar' => 'باد هيرسفيلد',
                'de' => 'Bad Hersfeld',
                'fr' => 'Bad Hersfeld',
                'it' => 'Bad Hersfeld',
            ],
            [
                'en' => 'Bebra',
                'ar' => 'بيبرا',
                'de' => 'Bebra',
                'fr' => 'Bebra',
                'it' => 'Bebra',
            ],
            [
                'en' => 'Rotenburg',
                'ar' => 'روتنبورغ',
                'de' => 'Rotenburg',
                'fr' => 'Rotenburg',
                'it' => 'Rotenburg',
            ],
            [
                'en' => 'Sontra',
                'ar' => 'زونترا',
                'de' => 'Sontra',
                'fr' => 'Sontra',
                'it' => 'Sontra',
            ],
            [
                'en' => 'Waldkappel',
                'ar' => 'فالدكابيل',
                'de' => 'Waldkappel',
                'fr' => 'Waldkappel',
                'it' => 'Waldkappel',
            ],
            [
                'en' => 'Eschwege',
                'ar' => 'إشفايج',
                'de' => 'Eschwege',
                'fr' => 'Eschwege',
                'it' => 'Eschwege',
            ],
            [
                'en' => 'Witzenhausen',
                'ar' => 'فيتزنهاوزن',
                'de' => 'Witzenhausen',
                'fr' => 'Witzenhausen',
                'it' => 'Witzenhausen',
            ],
            [
                'en' => 'Hessisch Lichtenau',
                'ar' => 'هيسيش ليشتنآو',
                'de' => 'Hessisch Lichtenau',
                'fr' => 'Hessisch Lichtenau',
                'it' => 'Hessisch Lichtenau',
            ],
            [
                'en' => 'Spangenberg',
                'ar' => 'شبانغنبرغ',
                'de' => 'Spangenberg',
                'fr' => 'Spangenberg',
                'it' => 'Spangenberg',
            ],
            [
                'en' => 'Melsungen',
                'ar' => 'ميلسونغن',
                'de' => 'Melsungen',
                'fr' => 'Melsungen',
                'it' => 'Melsungen',
            ],
            [
                'en' => 'Felsberg',
                'ar' => 'فيلسبيرغ',
                'de' => 'Felsberg',
                'fr' => 'Felsberg',
                'it' => 'Felsberg',
            ],
            [
                'en' => 'Gudensberg',
                'ar' => 'غودنسبيرغ',
                'de' => 'Gudensberg',
                'fr' => 'Gudensberg',
                'it' => 'Gudensberg',
            ],
            [
                'en' => 'Niedenstein',
                'ar' => 'نيدنشتاين',
                'de' => 'Niedenstein',
                'fr' => 'Niedenstein',
                'it' => 'Niedenstein',
            ],
            [
                'en' => 'Fritzlar',
                'ar' => 'فريتسار',
                'de' => 'Fritzlar',
                'fr' => 'Fritzlar',
                'it' => 'Fritzlar',
            ],
            [
                'en' => 'Homberg',
                'ar' => 'هومبرغ',
                'de' => 'Homberg',
                'fr' => 'Homberg',
                'it' => 'Homberg',
            ],
            [
                'en' => 'Schwalmstadt',
                'ar' => 'شفالمشتات',
                'de' => 'Schwalmstadt',
                'fr' => 'Schwalmstadt',
                'it' => 'Schwalmstadt',
            ],
            [
                'en' => 'Neukirchen',
                'ar' => 'نويكيرشن',
                'de' => 'Neukirchen',
                'fr' => 'Neukirchen',
                'it' => 'Neukirchen',
            ],
            [
                'en' => 'Willingshausen',
                'ar' => 'فيلينغسهاوزن',
                'de' => 'Willingshausen',
                'fr' => 'Willingshausen',
                'it' => 'Willingshausen',
            ],
            [
                'en' => 'Gilserberg',
                'ar' => 'غيلسربيرغ',
                'de' => 'Gilserberg',
                'fr' => 'Gilserberg',
                'it' => 'Gilserberg',
            ],
            [
                'en' => 'Jesberg',
                'ar' => 'يسبرغ',
                'de' => 'Jesberg',
                'fr' => 'Jesberg',
                'it' => 'Jesberg',
            ],
            [
                'en' => 'Knüllwald',
                'ar' => 'كنولفالد',
                'de' => 'Knüllwald',
                'fr' => 'Knüllwald',
                'it' => 'Knüllwald',
            ],
            [
                'en' => 'Ottrau',
                'ar' => 'أوتراو',
                'de' => 'Ottrau',
                'fr' => 'Ottrau',
                'it' => 'Ottrau',
            ],
            [
                'en' => 'Schrecksbach',
                'ar' => 'شريكسباخ',
                'de' => 'Schrecksbach',
                'fr' => 'Schrecksbach',
                'it' => 'Schrecksbach',
            ],
            [
                'en' => 'Schwarzenborn',
                'ar' => 'شفارتسنبورن',
                'de' => 'Schwarzenborn',
                'fr' => 'Schwarzenborn',
                'it' => 'Schwarzenborn',
            ],
            [
                'en' => 'Ziegenhain',
                'ar' => 'تسيغنهاين',
                'de' => 'Ziegenhain',
                'fr' => 'Ziegenhain',
                'it' => 'Ziegenhain',
            ],
            [
                'en' => 'Treysa',
                'ar' => 'ترايسا',
                'de' => 'Treysa',
                'fr' => 'Treysa',
                'it' => 'Treysa',
            ],
            [
                'en' => 'Zwesten',
                'ar' => 'تسفستن',
                'de' => 'Zwesten',
                'fr' => 'Zwesten',
                'it' => 'Zwesten',
            ],
            [
                'en' => 'Bad Zwesten',
                'ar' => 'باد تسفستن',
                'de' => 'Bad Zwesten',
                'fr' => 'Bad Zwesten',
                'it' => 'Bad Zwesten',
            ],
            [
                'en' => 'Bad Wildungen',
                'ar' => 'باد فيلدونغن',
                'de' => 'Bad Wildungen',
                'fr' => 'Bad Wildungen',
                'it' => 'Bad Wildungen',
            ],
            [
                'en' => 'Edertal',
                'ar' => 'إيدرتال',
                'de' => 'Edertal',
                'fr' => 'Edertal',
                'it' => 'Edertal',
            ],
            [
                'en' => 'Vöhl',
                'ar' => 'فول',
                'de' => 'Vöhl',
                'fr' => 'Vöhl',
                'it' => 'Vöhl',
            ],
            [
                'en' => 'Waldeck',
                'ar' => 'فالديك',
                'de' => 'Waldeck',
                'fr' => 'Waldeck',
                'it' => 'Waldeck',
            ],
            [
                'en' => 'Twistetal',
                'ar' => 'تفيستتال',
                'de' => 'Twistetal',
                'fr' => 'Twistetal',
                'it' => 'Twistetal',
            ],
            [
                'en' => 'Diemelsee',
                'ar' => 'ديميلزي',
                'de' => 'Diemelsee',
                'fr' => 'Diemelsee',
                'it' => 'Diemelsee',
            ],
            [
                'en' => 'Diemelstadt',
                'ar' => 'ديميلشتات',
                'de' => 'Diemelstadt',
                'fr' => 'Diemelstadt',
                'it' => 'Diemelstadt',
            ],
            [
                'en' => 'Marsberg',
                'ar' => 'مارسبيرغ',
                'de' => 'Marsberg',
                'fr' => 'Marsberg',
                'it' => 'Marsberg',
            ],
            [
                'en' => 'Obermarsberg',
                'ar' => 'أوبرمارسبيرغ',
                'de' => 'Obermarsberg',
                'fr' => 'Obermarsberg',
                'it' => 'Obermarsberg',
            ],
            [
                'en' => 'Niedermarsberg',
                'ar' => 'نيدرمارسبيرغ',
                'de' => 'Niedermarsberg',
                'fr' => 'Niedermarsberg',
                'it' => 'Niedermarsberg',
            ],
            [
                'en' => 'Erwitte',
                'ar' => 'إرفيت',
                'de' => 'Erwitte',
                'fr' => 'Erwitte',
                'it' => 'Erwitte',
            ],
            [
                'en' => 'Geseke',
                'ar' => 'غيزيك',
                'de' => 'Geseke',
                'fr' => 'Geseke',
                'it' => 'Geseke',
            ],
            [
                'en' => 'Lippstadt',
                'ar' => 'ليبشتات',
                'de' => 'Lippstadt',
                'fr' => 'Lippstadt',
                'it' => 'Lippstadt',
            ],
            [
                'en' => 'Rüthen',
                'ar' => 'روتن',
                'de' => 'Rüthen',
                'fr' => 'Rüthen',
                'it' => 'Rüthen',
            ],
            [
                'en' => 'Warstein',
                'ar' => 'فارشتاين',
                'de' => 'Warstein',
                'fr' => 'Warstein',
                'it' => 'Warstein',
            ],
            [
                'en' => 'Soest',
                'ar' => 'زوست',
                'de' => 'Soest',
                'fr' => 'Soest',
                'it' => 'Soest',
            ],
            [
                'en' => 'Werl',
                'ar' => 'فيرل',
                'de' => 'Werl',
                'fr' => 'Werl',
                'it' => 'Werl',
            ],
            [
                'en' => 'Wickede',
                'ar' => 'فيكيد',
                'de' => 'Wickede',
                'fr' => 'Wickede',
                'it' => 'Wickede',
            ],
            [
                'en' => 'Fröndenberg',
                'ar' => 'فروندنبرغ',
                'de' => 'Fröndenberg',
                'fr' => 'Fröndenberg',
                'it' => 'Fröndenberg',
            ],
            [
                'en' => 'Menden',
                'ar' => 'مندن',
                'de' => 'Menden',
                'fr' => 'Menden',
                'it' => 'Menden',
            ],
            [
                'en' => 'Balve',
                'ar' => 'بالفه',
                'de' => 'Balve',
                'fr' => 'Balve',
                'it' => 'Balve',
            ],
            [
                'en' => 'Sundern',
                'ar' => 'زوندرن',
                'de' => 'Sundern',
                'fr' => 'Sundern',
                'it' => 'Sundern',
            ],
            [
                'en' => 'Arnsberg',
                'ar' => 'أرنسبيرغ',
                'de' => 'Arnsberg',
                'fr' => 'Arnsberg',
                'it' => 'Arnsberg',
            ],
            [
                'en' => 'Neheim-Hüsten',
                'ar' => 'نيهيم-هوستن',
                'de' => 'Neheim-Hüsten',
                'fr' => 'Neheim-Hüsten',
                'it' => 'Neheim-Hüsten',
            ],
            [
                'en' => 'Sundern',
                'ar' => 'زوندرن',
                'de' => 'Sundern',
                'fr' => 'Sundern',
                'it' => 'Sundern',
            ],
            [
                'en' => 'Eslohe',
                'ar' => 'إسلو',
                'de' => 'Eslohe',
                'fr' => 'Eslohe',
                'it' => 'Eslohe',
            ],
            [
                'en' => 'Finnentrop',
                'ar' => 'فينينتروب',
                'de' => 'Finnentrop',
                'fr' => 'Finnentrop',
                'it' => 'Finnentrop',
            ],
            [
                'en' => 'Lennestadt',
                'ar' => 'لينستات',
                'de' => 'Lennestadt',
                'fr' => 'Lennestadt',
                'it' => 'Lennestadt',
            ],
            [
                'en' => 'Kirchhundem',
                'ar' => 'كيرشهوندم',
                'de' => 'Kirchhundem',
                'fr' => 'Kirchhundem',
                'it' => 'Kirchhundem',
            ],
            [
                'en' => 'Attendorn',
                'ar' => 'آتيندورن',
                'de' => 'Attendorn',
                'fr' => 'Attendorn',
                'it' => 'Attendorn',
            ],
            [
                'en' => 'Olpe',
                'ar' => 'أولبي',
                'de' => 'Olpe',
                'fr' => 'Olpe',
                'it' => 'Olpe',
            ],
            [
                'en' => 'Drolshagen',
                'ar' => 'دولشاغن',
                'de' => 'Drolshagen',
                'fr' => 'Drolshagen',
                'it' => 'Drolshagen',
            ],
            [
                'en' => 'Wenden',
                'ar' => 'فندن',
                'de' => 'Wenden',
                'fr' => 'Wenden',
                'it' => 'Wenden',
            ],
            [
                'en' => 'Freudenberg',
                'ar' => 'فرويدنبرغ',
                'de' => 'Freudenberg',
                'fr' => 'Freudenberg',
                'it' => 'Freudenberg',
            ],
            [
                'en' => 'Siegen',
                'ar' => 'زيغن',
                'de' => 'Siegen',
                'fr' => 'Siegen',
                'it' => 'Siegen',
            ],
            [
                'en' => 'Netphen',
                'ar' => 'نيتفن',
                'de' => 'Netphen',
                'fr' => 'Netphen',
                'it' => 'Netphen',
            ],
            [
                'en' => 'Hilchenbach',
                'ar' => 'هيلشنباخ',
                'de' => 'Hilchenbach',
                'fr' => 'Hilchenbach',
                'it' => 'Hilchenbach',
            ],
            [
                'en' => 'Bad Berleburg',
                'ar' => 'باد برليبورغ',
                'de' => 'Bad Berleburg',
                'fr' => 'Bad Berleburg',
                'it' => 'Bad Berleburg',
            ],
            [
                'en' => 'Bad Laasphe',
                'ar' => 'باد لاسب',
                'de' => 'Bad Laasphe',
                'fr' => 'Bad Laasphe',
                'it' => 'Bad Laasphe',
            ],
            [
                'en' => 'Erndtebrück',
                'ar' => 'إرندتيبروك',
                'de' => 'Erndtebrück',
                'fr' => 'Erndtebrück',
                'it' => 'Erndtebrück',
            ],
            [
                'en' => 'Burbach',
                'ar' => 'بورباخ',
                'de' => 'Burbach',
                'fr' => 'Burbach',
                'it' => 'Burbach',
            ],
            [
                'en' => 'Neunkirchen',
                'ar' => 'نوينكيرشن',
                'de' => 'Neunkirchen',
                'fr' => 'Neunkirchen',
                'it' => 'Neunkirchen',
            ],
            [
                'en' => 'Wilnsdorf',
                'ar' => 'فيلنسدورف',
                'de' => 'Wilnsdorf',
                'fr' => 'Wilnsdorf',
                'it' => 'Wilnsdorf',
            ],
            [
                'en' => 'Burbach',
                'ar' => 'بورباخ',
                'de' => 'Burbach',
                'fr' => 'Burbach',
                'it' => 'Burbach',
            ],
            [
                'en' => 'Eschenbach',
                'ar' => 'إشينباخ',
                'de' => 'Eschenbach',
                'fr' => 'Eschenbach',
                'it' => 'Eschenbach',
            ],
            [
                'en' => 'Freudenberg',
                'ar' => 'فرويدنبرغ',
                'de' => 'Freudenberg',
                'fr' => 'Freudenberg',
                'it' => 'Freudenberg',
            ],
            [
                'en' => 'Kreuztal',
                'ar' => 'كروتسالتال',
                'de' => 'Kreuztal',
                'fr' => 'Kreuztal',
                'it' => 'Kreuztal',
            ],
            [
                'en' => 'Krombach',
                'ar' => 'كرومباخ',
                'de' => 'Krombach',
                'fr' => 'Krombach',
                'it' => 'Krombach',
            ],
            [
                'en' => 'Lennestadt',
                'ar' => 'لينستات',
                'de' => 'Lennestadt',
                'fr' => 'Lennestadt',
                'it' => 'Lennestadt',
            ],
            [
                'en' => 'Müsen',
                'ar' => 'موسن',
                'de' => 'Müsen',
                'fr' => 'Müsen',
                'it' => 'Müsen',
            ],
            [
                'en' => 'Niederdielfen',
                'ar' => 'نيدرديلفن',
                'de' => 'Niederdielfen',
                'fr' => 'Niederdielfen',
                'it' => 'Niederdielfen',
            ],
            [
                'en' => 'Oberdielfen',
                'ar' => 'أوبرديلفن',
                'de' => 'Oberdielfen',
                'fr' => 'Oberdielfen',
                'it' => 'Oberdielfen',
            ],
            [
                'en' => 'Rödgen',
                'ar' => 'رودغن',
                'de' => 'Rödgen',
                'fr' => 'Rödgen',
                'it' => 'Rödgen',
            ],
            [
                'en' => 'Rudersdorf',
                'ar' => 'رودرسدورف',
                'de' => 'Rudersdorf',
                'fr' => 'Rudersdorf',
                'it' => 'Rudersdorf',
            ],
            [
                'en' => 'Salchendorf',
                'ar' => 'زالشندورف',
                'de' => 'Salchendorf',
                'fr' => 'Salchendorf',
                'it' => 'Salchendorf',
            ],
            [
                'en' => 'Seelbach',
                'ar' => 'زيلباخ',
                'de' => 'Seelbach',
                'fr' => 'Seelbach',
                'it' => 'Seelbach',
            ],
            [
                'en' => 'Steinbach',
                'ar' => 'شتاينباخ',
                'de' => 'Steinbach',
                'fr' => 'Steinbach',
                'it' => 'Steinbach',
            ],
            [
                'en' => 'Trupbach',
                'ar' => 'تروبباخ',
                'de' => 'Trupbach',
                'fr' => 'Trupbach',
                'it' => 'Trupbach',
            ],
            [
                'en' => 'Volnsberg',
                'ar' => 'فولنسبيرغ',
                'de' => 'Volnsberg',
                'fr' => 'Volnsberg',
                'it' => 'Volnsberg',
            ],
            [
                'en' => 'Weidenau',
                'ar' => 'فايدناو',
                'de' => 'Weidenau',
                'fr' => 'Weidenau',
                'it' => 'Weidenau',
            ],
            [
                'en' => 'Weisbach',
                'ar' => 'فايسباخ',
                'de' => 'Weisbach',
                'fr' => 'Weisbach',
                'it' => 'Weisbach',
            ],
            [
                'en' => 'Wilden',
                'ar' => 'فيلدن',
                'de' => 'Wilden',
                'fr' => 'Wilden',
                'it' => 'Wilden',
            ],
            [
                'en' => 'Wilgersdorf',
                'ar' => 'فيلغيرسدورف',
                'de' => 'Wilgersdorf',
                'fr' => 'Wilgersdorf',
                'it' => 'Wilgersdorf',
            ],
            [
                'en' => 'Wilnsdorf',
                'ar' => 'فيلنسدورف',
                'de' => 'Wilnsdorf',
                'fr' => 'Wilnsdorf',
                'it' => 'Wilnsdorf',
            ],
            [
                'en' => 'Wissen',
                'ar' => 'فيسن',
                'de' => 'Wissen',
                'fr' => 'Wissen',
                'it' => 'Wissen',
            ],
            [
                'en' => 'Zinse',
                'ar' => 'تسينزي',
                'de' => 'Zinse',
                'fr' => 'Zinse',
                'it' => 'Zinse',
            ],
        ];

        // إضافة جميع المدن
        foreach ($cities as $cityData) {
            City::firstOrCreate(
                [
                    'country_id' => $germany->id,
                    'name' => $cityData
                ]
            );
        }

        $this->command->info('Germany country and all major cities have been seeded successfully!');
    }
}
